sudo: false

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.2
    - cabal-install-1.22

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - export PATH=/opt/ghc/7.10.2/bin:/opt/cabal/1.22/bin:$PATH

install:
 - ls /opt/ghc
 - ls /opt/ghc/7.10.2/bin
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - wget https://s3.amazonaws.com/stackage-travis/stackage-curator/stackage-curator.bz2
 - bunzip2 stackage-curator.bz2
 - chmod +x stackage-curator

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - ./stackage-curator check
